version: "3.7"
services:
  app:
    build:
      args:
        user: application-model
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: application-model
    container_name: application-model-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - application-model

  nginx:
    image: nginx:1.17-alpine
    container_name: application-model-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - application-model

  postgres-compose:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 15432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    networks:
      - application-model

  pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgmail@mail.com.br"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin!"
    ports:
      - 16543:80
    depends_on:
      - postgres-compose
    networks:
      - application-model

networks:
  application-model:
    driver: bridge